spring:
  application:
    name: magis5-challenge

  datasource:
    url: jdbc:mysql://localhost:3306/magis5_db?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /